In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Cleaned_Sales_Dataset.csv")

In [5]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,Age_Group,Month
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,Adult,February
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,Senior,October
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,Senior,May
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,Senior,December
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,Middle Age,November

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            1000 non-null   float64
 5   Gender         1000 non-null   object
 6   City           1000 non-null   object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
 12  Age_Group      1000 non-null   object
 13  Month          1000 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 109.5+ KB

In [7]:
df.describe()

               Age     Quantity    Unit_Price    Total_Sales
count  1000.000000  1000.000000   1000.000000    1000.000000
mean     41.353000     5.435000  25486.783410  139399.439650
std      13.683626     2.838632  14179.402361  114100.051546
min      18.000000     1.000000    145.780000     437.340000
25%      30.000000     3.000000  13895.722500   47066.632500
50%      41.000000     5.000000  25398.740000  108594.025000
75%      53.000000     8.000000  37512.382500  203722.882500
max      65.000000    10.000000  49997.530000  493677.500000

#Define Core KPIs

In [8]:
#Total Revenue
total_revenue = df['Total_Sales'].sum()

print("Total Revenue :", total_revenue)

Total Revenue : 139399439.65

In [9]:
#Total Orders
total_orders = df['Order_ID'].nunique()

print("Total Orders :", total_orders)

Total Orders : 992

In [10]:
# Total Customers
total_customers = df['Customer_ID'].nunique()

print("Total Customers :", total_customers)

Total Customers : 947

In [11]:
#Average Order Value
average_order_value = total_revenue / total_orders

print("Average Order Value :", round(average_order_value,2))

Average Order Value : 140523.63

In [12]:
# Total Quantity Sold
total_quantity = df['Quantity'].sum()

print("Total Quantity Sold :", total_quantity)

Total Quantity Sold : 5435

In [13]:
#Average Quantity Per Order
avg_quantity = df['Quantity'].mean()

print("Average Quantity :", round(avg_quantity,2))

Average Quantity : 5.44

In [14]:
#Highest Revenue Category
highest_category = df.groupby('Category')['Total_Sales'].sum().sort_values(ascending=False)

print(highest_category)

Category
Electronics    50778581.70
Education      25031689.40
Grocery        22231711.28
Furniture      21521561.48
Fashion        19835895.79
Name: Total_Sales, dtype: float64

In [15]:
#Highest Revenue City
highest_city = df.groupby('City')['Total_Sales'].sum().sort_values(ascending=False)

print(highest_city)

City
Patna        20826584.43
Kolkata      18884349.57
Bengaluru    18773574.32
Mumbai       18757050.17
Hyderabad    17166766.87
Delhi        16097079.00
Pune         14513175.90
Gaya         14380859.39
Name: Total_Sales, dtype: float64

In [16]:
# Top 5 Products
top_products = df.groupby('Product')['Total_Sales'].sum().sort_values(ascending=False).head(5)

print(top_products)

Product
Laptop    25443008.51
Mobile    25335573.19
Book      25031689.40
Rice      22231711.28
Chair     21521561.48
Name: Total_Sales, dtype: float64

In [17]:
#Customer Lifetime Value
clv = df.groupby('Customer_ID')['Total_Sales'].sum().mean()

print("Customer Lifetime Value :", round(clv,2))

Customer Lifetime Value : 147201.1

In [18]:
#Repeat Customers
repeat_customers = df.groupby('Customer_ID').size()

repeat_customers = repeat_customers[repeat_customers>1].count()

print("Repeat Customers :", repeat_customers)

Repeat Customers : 52

In [19]:
#Repeat Customer Rate
repeat_rate = (repeat_customers/total_customers)*100

print("Repeat Customer Rate :", round(repeat_rate,2),"%")

Repeat Customer Rate : 5.49 %

In [20]:
print("="*50)
print("          CORE KPIs")
print("="*50)

print(f"Total Revenue           : {total_revenue:,.2f}")
print(f"Total Orders            : {total_orders}")
print(f"Total Customers         : {total_customers}")
print(f"Average Order Value     : {average_order_value:.2f}")
print(f"Total Quantity Sold     : {total_quantity}")
print(f"Average Quantity        : {avg_quantity:.2f}")
print(f"Customer Lifetime Value : {clv:.2f}")
print(f"Repeat Customer Rate    : {repeat_rate:.2f}%")

==================================================
          CORE KPIs
==================================================
Total Revenue           : 139,399,439.65
Total Orders            : 992
Total Customers         : 947
Average Order Value     : 140523.63
Total Quantity Sold     : 5435
Average Quantity        : 5.43
Customer Lifetime Value : 147201.10
Repeat Customer Rate    : 5.49%